import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { constants } from "node:fs";
import path from "node:path";
import fs from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

interface Asset {
  from: string;
  to: string;
}

interface CopyStaticAssetsPluginOptions {
  assets: Asset[];
}

function copyStaticAssetsPlugin(opts: CopyStaticAssetsPluginOptions): esbuild.Plugin {
  return {
    name: "copy-static-files",
    setup(build) {
      const { assets } = opts;

      const outDir = build.initialOptions.outdir;
      const srcBaseDir = build.initialOptions.absWorkingDir ?? "";

      if (outDir === undefined) {
        throw new Error("esbuild.options.outDir is not specified");
      }

      const absolutePathAssets: Asset[] = assets.map(({ from, to }) => {
        const src = path.resolve(srcBaseDir, from);
        const dest = path.resolve(outDir, to);
        return { from: src, to: dest };
      });
      const destDirs = new Set(absolutePathAssets.map(({ to }) => path.resolve(to, "..")));

      build.onEnd(async (result) => {
        if (result.errors.length > 0) return;

        await Promise.all(
          Array.from(destDirs, (destDir) => {
            return fs.promises.mkdir(destDir, { recursive: true });
          }),
        );
        await Promise.all(
          absolutePathAssets.map(({ from, to }) => {
            return fs.promises.copyFile(from, to, constants.COPYFILE_FICLONE);
          }),
        );
      });
    },
  };
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  minify: prod,
  plugins: [
    copyStaticAssetsPlugin({
      assets: [
        { from: "styles.css", to: "styles.css" },
        { from: "manifest.json", to: "manifest.json" },
      ],
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
